operate-first/support

README.md
docs/user-docs/jupyterhub.md

Adding user documentation for JH into `docs/user-docs`

Add user documentation for JH

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/task.md

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
Fixes: https://github.com/operate-first/odh-moc-support/issues/3

Add issue templates

---

README.md

Reflect the most recent ODH state better

chore: Update status board

---

.github/ISSUE_TEMPLATE/onboarding_argocd.md

Part of: #39 
Adds an issue template checklist/questionnaire for Argo CD onboarding

chore: Add issue template for Argo CD onboarding

---

docs/claiming_object_store.md

docs: Add onboarding docs for rook

---

.github/ISSUE_TEMPLATE/onboarding_argocd.md

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

update wrong links that gives 404

---

.github/ISSUE_TEMPLATE/onboarding_argocd.md

Add a section for adding users to argocd onboarding template

---

.github/ISSUE_TEMPLATE/request_cluster_resources.md

Resolves: https://github.com/operate-first/support/issues/64

chore: Add issue template for general cluster scoped resource request

---

README.md

make README more generic and add kubeflow apps in app list

---

README.md

Fixes https://github.com/operate-first/support/issues/94

Fix website URL

---

README.md

Part of: https://github.com/operate-first/SRE/issues/108

Update links to point to new zero cluster.

---

docs/onboarding_to_cluster.md

Docs for: https://github.com/operate-first/blueprint/issues/45

chore: Rename hack to scripts folder

---

README.md

Should be merged once the password is updated via ui on live deployement.

Update generic password for hue/superset.

---

.github/ISSUE_TEMPLATE/onboarding_to_cluster.md

Fixes: https://github.com/operate-first/support/issues/129

Clarify onboarding issue template.

---

README.md

Part of: https://github.com/operate-first/apps/issues/192

feat: Show the nice URL for a dashboard on the support readme

---

docs/onboarding_to_argocd.md

Related: https://github.com/operate-first/continuous-deployment/issues/113

Update argocd docs and links to new location.

---

.github/ISSUE_TEMPLATE/onboarding_to_cluster.md
docs/quotas.md

Related: https://github.com/operate-first/apps/pull/488 , https://github.com/operate-first/blueprint/pull/65

Add quota tiers doc.

---

docs/quotas.md

As per: https://github.com/operate-first/apps/pull/507#pullrequestreview-633433990

Add x-small quota to docs

---

README.md
docs/kubeflow/README.md
docs/odh/README.md
docs/onboarding_to_cluster.md

Related Issues: 
- https://github.com/operate-first/blueprint/issues/62#issuecomment-814919133 
- https://github.com/operate-first/support/issues/124
I've extracted odh/kubeflow stuff to be in it's own readme, and link to them from the root readme. I've also added the various services that users may find useful to know about. Let me know if I've missed anything. 
For the ODH/Kubeflow readme's, I've removed the chart since I didn't think it was very useful.

Update readme and odh/kubeflow docs.

---

docs/onboarding_to_argocd.md

Resolve: https://github.com/operate-first/support/issues/197

Clarify argocd onboarding instructions.

---

README.md

Reflecting changes in: https://github.com/operate-first/apps/pull/580 and https://github.com/operate-first/apps/pull/577 in the readme.

Update readme with monitoring restriction notice.

---

docs/onboarding_to_cluster.md

Also removed some bloat/unnecessary info that's not  directly relevant to the steps: 
related: 
- https://github.com/operate-first/apps/pull/622
- https://github.com/operate-first/apps/issues/631

Update onboarding cluster docs to reflect adr 15

---

docs/onboarding_to_cluster.md

Related: https://github.com/operate-first/apps/issues/760
Also removed the use of `kustomize edit add` so we can have people add it alphabetically (also avoid reformatting the kustomization making the diff unnecessarily large).

Update onboarding doc to use cli.

---

.github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml

Onboard Freeze Notice for template

---

README.md

Part of: https://github.com/operate-first/hetzner-baremetal-openshift/issues/12

feat: Add Rick

---

docs/onboarding_to_cluster.md

Fix outdated links in onboarding cluster doc.

---

docs/odh/README.md
docs/trino_superset_user_guide.md

Update outdated links to odh services.

---

README.md

After #325 md files were converted to yamls

readme: update onboarding links

---

docs/trino_superset_user_guide.md

Update superset doc

---

README.md

This pr makes various changes to the readme based on the updated situation with the smaug cluster.
Part of https://github.com/operate-first/SRE/issues/403

Readme edits for smaug

---

.github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml

Resolve: https://github.com/operate-first/support/issues/468

Add uptdated quotas link for onboarding docs.

---

.github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml

Related: https://github.com/operate-first/SRE/issues/439#issuecomment-1015454797

Update outdated links in onboarding template.

---

.github/ISSUE_TEMPLATE/onboarding_to_cluster.yaml

Reverts operate-first/support#301
/cc @HumairAK @4n4nd @larsks

Revert "Onboard Freeze Notice for template"

---

.github/ISSUE_TEMPLATE/4_onboarding_to_cluster.yaml

Resolve: https://github.com/operate-first/support/issues/547

Remove morty and gpg contract field in onboarding.

---

.github/ISSUE_TEMPLATE/4_onboarding_to_cluster.yaml
.github/ISSUE_TEMPLATE/5_offboarding_from_a_cluster.yaml

Signed-off-by: Eric Ball <eball@linuxfoundation.org>

Add OSC clusters to onboarding/offboarding options
